# Generated by Django 5.1.5 on 2026-01-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='booking_type',
            field=models.CharField(choices=[('individual', 'Individual Booking'), ('room_pool', 'Room Pool Booking')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_room_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='pool_members_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservation',
            name='room_pool_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
