# Generated by Django 5.1.5 on 2025-05-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clerk_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
