# Generated by Django 5.1.5 on 2026-01-14 08:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('property', '0002_property_available_hours_end_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoommateProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('no_preference', 'No Preference')], default='no_preference', max_length=20)),
                ('preferred_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('no_preference', 'No Preference')], default='no_preference', max_length=20)),
                ('age_group', models.CharField(blank=True, choices=[('18_25', '18-25'), ('26_35', '26-35'), ('36_45', '36-45'), ('46_55', '46-55'), ('56_plus', '56+')], max_length=20)),
                ('preferred_age_groups', models.JSONField(default=list)),
                ('sleep_schedule', models.CharField(choices=[('early_bird', 'Early Bird (Sleep before 10pm)'), ('night_owl', 'Night Owl (Sleep after midnight)'), ('flexible', 'Flexible')], default='flexible', max_length=20)),
                ('cleanliness', models.CharField(choices=[('very_clean', 'Very Clean & Organized'), ('moderate', 'Moderately Clean'), ('relaxed', 'Relaxed about cleanliness')], default='moderate', max_length=20)),
                ('noise_preference', models.CharField(choices=[('quiet', 'Prefer Quiet Environment'), ('moderate', 'Some noise is fine'), ('social', 'Love socializing & noise')], default='moderate', max_length=20)),
                ('smoking', models.CharField(choices=[('non_smoker', 'Non-Smoker'), ('smoker', 'Smoker'), ('outdoor_only', 'Outdoor Smoker Only'), ('no_preference', 'No Preference')], default='no_preference', max_length=20)),
                ('interests', models.JSONField(default=list)),
                ('languages', models.JSONField(default=list)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('pets_allowed', models.BooleanField(default=False)),
                ('has_pets', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('is_looking_for_roommate', models.BooleanField(default=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_active'],
            },
        ),
        migrations.CreateModel(
            name='RoomPool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('max_members', models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(20)])),
                ('current_members', models.IntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_fee_per_person', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('open', 'Open - Accepting Members'), ('full', 'Full - No More Spots'), ('closed', 'Closed - Not Accepting'), ('booked', 'Booked - Reservation Made'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public - Anyone can find and request'), ('private', 'Private - Invite only'), ('friends', 'Friends Only')], default='public', max_length=20)),
                ('gender_preference', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('no_preference', 'No Preference')], default='no_preference', max_length=20)),
                ('min_age', models.IntegerField(blank=True, null=True)),
                ('max_age', models.IntegerField(blank=True, null=True)),
                ('smoking_allowed', models.BooleanField(default=False)),
                ('pets_allowed', models.BooleanField(default=False)),
                ('use_compatibility_matching', models.BooleanField(default=True)),
                ('min_compatibility_score', models.IntegerField(default=50)),
                ('booking_deadline', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_pools', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_pools', to='property.property')),
                ('reservation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_pool', to='booking.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PoolInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invited_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, max_length=500)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_pool_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pool_invitations', to=settings.AUTH_USER_MODEL)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='roompooling.roompool')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PoolChat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('text', 'Text Message'), ('system', 'System Message'), ('payment', 'Payment Update'), ('join', 'Member Joined'), ('leave', 'Member Left')], default='text', max_length=20)),
                ('message', models.TextField(max_length=1000)),
                ('metadata', models.JSONField(default=dict)),
                ('is_read_by', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pool_messages', to=settings.AUTH_USER_MODEL)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='roompooling.roompool')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CostSplit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('split_type', models.CharField(choices=[('equal', 'Equal Split'), ('custom', 'Custom Percentages'), ('by_nights', 'Split by Nights Stayed'), ('by_beds', 'Split by Bed Allocation')], default='equal', max_length=20)),
                ('base_accommodation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cleaning_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custom_percentages', models.JSONField(default=dict)),
                ('individual_amounts', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost_split', to='roompooling.roompool')),
            ],
        ),
        migrations.CreateModel(
            name='RoomPoolMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('left', 'Left Pool'), ('removed', 'Removed by Creator')], default='pending', max_length=20)),
                ('is_creator', models.BooleanField(default=False)),
                ('compatibility_score', models.IntegerField(default=0)),
                ('share_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Payment Pending'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_due_date', models.DateTimeField(blank=True, null=True)),
                ('custom_split_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('request_message', models.TextField(blank=True, max_length=500)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='roompooling.roompool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
                'unique_together': {('pool', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], default='payment', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('pool_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='roompooling.roompoolmember')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
