# Generated by Django 5.1.5 on 2025-05-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='available_hours_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='available_hours_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='is_hourly_booking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='price_per_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
