# Generated by Django 5.1.5 on 2026-01-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_available_hours_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='allow_room_pooling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='max_pool_members',
            field=models.IntegerField(blank=True, default=6, null=True),
        ),
    ]
