# Generated by Django 5.1.5 on 2026-01-01 10:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('property', '0002_property_available_hours_end_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=255)),
                ('message_type', models.CharField(choices=[('user', 'User'), ('bot', 'Bot'), ('system', 'System')], max_length=10)),
                ('message', models.TextField()),
                ('intent', models.CharField(choices=[('greeting', 'Greeting'), ('search_property', 'Search Property'), ('booking_help', 'Booking Help'), ('price_inquiry', 'Price Inquiry'), ('recommendation', 'Recommendation'), ('itinerary', 'Itinerary Planning'), ('support', 'Support'), ('general', 'General')], default='general', max_length=30)),
                ('extracted_entities', models.JSONField(default=dict)),
                ('suggested_properties', models.JSONField(default=list)),
                ('was_helpful', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('activities', models.JSONField(default=list)),
                ('restaurants', models.JSONField(default=list)),
                ('attractions', models.JSONField(default=list)),
                ('transportation', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('ai_suggestions', models.JSONField(default=list)),
                ('weather_forecast', models.JSONField(default=dict)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itineraries', to='property.property')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itineraries', to='booking.reservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationPriceIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('january_index', models.FloatField(default=1.0)),
                ('february_index', models.FloatField(default=1.0)),
                ('march_index', models.FloatField(default=1.0)),
                ('april_index', models.FloatField(default=1.0)),
                ('may_index', models.FloatField(default=1.0)),
                ('june_index', models.FloatField(default=1.0)),
                ('july_index', models.FloatField(default=1.0)),
                ('august_index', models.FloatField(default=1.0)),
                ('september_index', models.FloatField(default=1.0)),
                ('october_index', models.FloatField(default=1.0)),
                ('november_index', models.FloatField(default=1.0)),
                ('december_index', models.FloatField(default=1.0)),
                ('cheapest_month', models.CharField(blank=True, max_length=20)),
                ('most_expensive_month', models.CharField(blank=True, max_length=20)),
                ('recommended_booking_advance', models.IntegerField(default=30)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('country', 'city')},
            },
        ),
        migrations.CreateModel(
            name='PropertyView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('view_duration', models.IntegerField(default=0)),
                ('viewed_images', models.BooleanField(default=False)),
                ('viewed_reviews', models.BooleanField(default=False)),
                ('added_to_wishlist', models.BooleanField(default=False)),
                ('initiated_booking', models.BooleanField(default=False)),
                ('completed_booking', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_views', to='property.property')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('search_query', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('guests_count', models.IntegerField(default=1)),
                ('min_price', models.IntegerField(blank=True, null=True)),
                ('max_price', models.IntegerField(blank=True, null=True)),
                ('results_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clicked_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.property')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred_categories', models.JSONField(default=list)),
                ('preferred_countries', models.JSONField(default=list)),
                ('min_bedrooms', models.IntegerField(default=1)),
                ('max_price_per_night', models.IntegerField(blank=True, null=True)),
                ('budget_preference', models.CharField(choices=[('budget', 'Budget-Friendly'), ('moderate', 'Moderate'), ('luxury', 'Luxury'), ('any', 'Any')], default='any', max_length=20)),
                ('travel_style', models.CharField(choices=[('adventure', 'Adventure'), ('relaxation', 'Relaxation'), ('business', 'Business'), ('family', 'Family'), ('romantic', 'Romantic'), ('solo', 'Solo')], default='relaxation', max_length=20)),
                ('preferred_amenities', models.JSONField(default=list)),
                ('typical_group_size', models.IntegerField(default=2)),
                ('prefers_pet_friendly', models.BooleanField(default=False)),
                ('prefers_accessibility', models.BooleanField(default=False)),
                ('price_drop_alerts', models.BooleanField(default=True)),
                ('new_listing_alerts', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GuestMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_match_score', models.FloatField(default=0)),
                ('category_match', models.FloatField(default=0)),
                ('price_match', models.FloatField(default=0)),
                ('location_match', models.FloatField(default=0)),
                ('amenities_match', models.FloatField(default=0)),
                ('style_match', models.FloatField(default=0)),
                ('match_reasons', models.JSONField(default=list)),
                ('is_viewed', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_matches', to='property.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-overall_match_score'],
                'unique_together': {('user', 'property')},
            },
        ),
        migrations.CreateModel(
            name='PriceTrend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('base_price', models.IntegerField()),
                ('actual_price', models.IntegerField()),
                ('is_weekend', models.BooleanField(default=False)),
                ('is_holiday', models.BooleanField(default=False)),
                ('is_peak_season', models.BooleanField(default=False)),
                ('local_event', models.CharField(blank=True, max_length=255)),
                ('demand_score', models.FloatField(default=1.0)),
                ('booking_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_trends', to='property.property')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('property', 'date')},
            },
        ),
    ]
