FROM python:3.12.9-bullseye

WORKDIR /usr/src/flexbnb_backend


ENV PYTHONDONTWRITEBYTECODE='1'
ENV PYTHONNUNBUFFERED='1'

RUN apt-get update && apt-get install -y netcat

RUN pip install --upgrade pip
COPY ./Requirements.txt .
RUN pip install -r Requirements.txt

COPY ./entrypoint.sh .
RUN sed -i 's/\r$//g' /usr/src/flexbnb_backend/entrypoint.sh
RUN chmod +x /usr/src/flexbnb_backend/entrypoint.sh

COPY . .

ENTRYPOINT [ "/usr/src/flexbnb_backend/entrypoint.sh" ]